"""games table

Revision ID: 16a1ab2a43de
Revises: 17b94d06247e
Create Date: 2020-04-10 09:52:00.629655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a1ab2a43de'
down_revision = '17b94d06247e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bgg_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_bgg_id'), 'game', ['bgg_id'], unique=True)
    op.create_index(op.f('ix_game_title'), 'game', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_title'), table_name='game')
    op.drop_index(op.f('ix_game_bgg_id'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
