"""games table

Revision ID: 17b94d06247e
Revises: def935b87137
Create Date: 2020-04-10 09:47:39.975998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17b94d06247e'
down_revision = 'def935b87137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'bgg_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('user', 'bgg_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
