"""empty message

Revision ID: 56b94b1d8cfd
Revises: 
Create Date: 2020-04-12 15:12:29.428796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b94b1d8cfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bgg_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_bgg_id'), 'game', ['bgg_id'], unique=True)
    op.create_index(op.f('ix_game_title'), 'game', ['title'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bgg_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bgg_id'), 'user', ['bgg_id'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_bgg_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_game_title'), table_name='game')
    op.drop_index(op.f('ix_game_bgg_id'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
