"""user_collection table

Revision ID: c9c3f4483ca5
Revises: 16a1ab2a43de
Create Date: 2020-04-10 11:14:27.979170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c3f4483ca5'
down_revision = '16a1ab2a43de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_collection_game_id'), 'user_collection', ['game_id'], unique=False)
    op.create_index(op.f('ix_user_collection_user_id'), 'user_collection', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_collection_user_id'), table_name='user_collection')
    op.drop_index(op.f('ix_user_collection_game_id'), table_name='user_collection')
    op.drop_table('user_collection')
    # ### end Alembic commands ###
